name: dh_segment_torch
channels:
  - default
  - pytorch
dependencies:
  - pip=19.3.1
  - setuptools=44.0.0
  - python=3.7
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.1
  - tensorboard=2.0.0
  - lxml=4.6.1
  - scikit-image=0.17.2
  - scikit-learn=0.22.2.post1
  - pandas=1.2.4
  - numpy=1.18.1
  - scipy=1.3.2
  - networkx=2.4
  - pip:
      - sacred=0.8.0
      - pretrainedmodels=0.7.4
      - opencv-python-headless=4.5.2.52
      - PyYaml=5.4.1
      - frozendict=2.0.2
      - albumentations=0.5.2
      - shapely=1.7.0
      - tqdm=4.60.0
      - requests=2.25.1
      - pytest=6.2.4
